// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Shenam.API.Brokers.Storages;

#nullable disable

namespace Shenam.API.Migrations
{
    [DbContext(typeof(StorageBroker))]
    partial class StorageBrokerModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Shenam.API.Models.Foundation.Guests.Guest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Guests");
                });

            modelBuilder.Entity("Shenam.API.Models.Foundation.HomeRequests.HomeRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");
                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("datetimeoffset");
                    b.Property<DateTimeOffset>("EndDate")
                        .HasColumnType("datetimeoffset");
                    b.Property<Guid>("GuestId")
                        .HasColumnType("uniqueidentifier");
                    b.Property<Guid>("HomeId")
                        .HasColumnType("uniqueidentifier");
                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)");
                    b.Property<DateTimeOffset>("StartDate")
                        .HasColumnType("datetimeoffset");
                    b.Property<DateTimeOffset>("UpdatedDate")
                        .HasColumnType("datetimeoffset");
                    b.HasKey("Id");
                    b.ToTable("HomeRequests");
                });
#pragma warning restore 612, 618
        }
    }
}
